import { MovieItem } from '../types';

export const MOVIE_COLLECTION: MovieItem[] = [
  { eng: "Baahubali", tamil: "பாகுபலி", hero: "Prabhas" },
  { eng: "Sivaji", tamil: "சிவாஜி", hero: "Rajinikanth" },
  { eng: "Mandalavaan", tamil: "மண்டலவான்", hero: "Pedro Pascal" },
  { eng: "Enthiran", tamil: "எந்திரன்", hero: "Rajinikanth" },
  { eng: "Vikram", tamil: "விக்ரம்", hero: "Kamal Haasan" },
  { eng: "Leo", tamil: "லியோ", hero: "Vijay" },
  { eng: "Muthu", tamil: "முத்து", hero: "Rajinikanth" },
  { eng: "Anniyan", tamil: "அந்நியன்", hero: "Vikram" },
  { eng: "Ghillie", tamil: "கில்லி", hero: "Vijay" },
  { eng: "Mankatha", tamil: "மங்காத்தா", hero: "Ajith" },
  { eng: "Thuppakki", tamil: "துப்பாக்கி", hero: "Vijay" },
  { eng: "Kathi", tamil: "கத்தி", hero: "Vijay" },
  { eng: "Master", tamil: "மாஸ்டர்", hero: "Vijay" },
  { eng: "Sarkar", tamil: "சர்க்கார்", hero: "Vijay" },
  { eng: "Billa", tamil: "பில்லா", hero: "Ajith" },
  { eng: "Viswasam", tamil: "விஸ்வாசம்", hero: "Ajith" },
  { eng: "Valimai", tamil: "வலிமை", hero: "Ajith" },
  { eng: "Petta", tamil: "பேட்ட", hero: "Rajinikanth" },
  { eng: "Darbar", tamil: "தர்பார்", hero: "Rajinikanth" },
  { eng: "Jailer", tamil: "ஜெயிலர்", hero: "Rajinikanth" },
  { eng: "Kabali", tamil: "கபாலி", hero: "Rajinikanth" },
  { eng: "Kaala", tamil: "காலா", hero: "Rajinikanth" },
  { eng: "2.0", tamil: "2.0", hero: "Rajinikanth" },
  { eng: "Gajini", tamil: "கஜினி", hero: "Suriya" },
  { eng: "Singam", tamil: "சிங்கம்", hero: "Suriya" },
  { eng: "Ayan", tamil: "அயன்", hero: "Suriya" },
  { eng: "Soorarai Pottru", tamil: "சூரரைப் போற்று", hero: "Suriya" },
  { eng: "Jai Bhim", tamil: "ஜெய் பீம்", hero: "Suriya" },
  { eng: "Vada Chennai", tamil: "வட சென்னை", hero: "Dhanush" },
  { eng: "Asuran", tamil: "அசுரன்", hero: "Dhanush" },
  { eng: "Aadukalam", tamil: "ஆடுகளம்", hero: "Dhanush" },
  { eng: "Polladhavan", tamil: "பொல்லாதவன்", hero: "Dhanush" },
  { eng: "Thiruchitrambalam", tamil: "திருச்சிற்றம்பலம்", hero: "Dhanush" },
  { eng: "Karnan", tamil: "கர்ணன்", hero: "Dhanush" },
  { eng: "Aatkal", tamil: "ஆட்கள்", hero: "Dhanush" },
  { eng: "Maanaadu", tamil: "மாநாடு", hero: "Silambarasan" },
  { eng: "Vendhu Thanindhathu Kaadu", tamil: "வெந்து தணிந்தது காடு", hero: "Silambarasan" },
  { eng: "Vinnaithaandi Varuvaayaa", tamil: "விண்ணைத்தாண்டி வருவாயா", hero: "Silambarasan" },
  { eng: "Doctor", tamil: "டாக்டர்", hero: "Sivakarthikeyan" },
  { eng: "Don", tamil: "டான்", hero: "Sivakarthikeyan" },
  { eng: "Maaveeran", tamil: "மாவீரன்", hero: "Sivakarthikeyan" },
  { eng: "Ayalaan", tamil: "அயலான்", hero: "Sivakarthikeyan" },
  { eng: "Varisu", tamil: "வாரிசு", hero: "Vijay" },
  { eng: "Thunivu", tamil: "துணிவு", hero: "Ajith" },
  { eng: "Mark Antony", tamil: "மார்க் ஆண்டனி", hero: "Vishal" },
  { eng: "Jigarthanda", tamil: "ஜிகர்தண்டா", hero: "Siddharth" },
  { eng: "Chithha", tamil: "சித்தா", hero: "Siddharth" },
  { eng: "Good Night", tamil: "குட் நைட்", hero: "K Manikandan" },
  { eng: "Dada", tamil: "டாடா", hero: "Kavin" },
  { eng: "Star", tamil: "ஸ்டார்", hero: "Kavin" }
];
